[Sprint 22/23 | PD-421] - [Enhancement] Use Jitsuyo For Utilities
ichiro-its/shisen pull request #28
Opened 2024-06-21 10:38 UTC by Mobilizes

## Jira Link: 
https://ichiro-its.atlassian.net/jira/software/c/projects/PD/boards/4?selectedIssue=PD-421

## Description
Use jitsuyo repository to load and save config

## Type of Change

- [ ] Bugfix
- [x] Enhancement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause the existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] New unit tests added.
- [ ] Manual tested.

## Checklist:

- [ ] Using Branch Name Convention
    - `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
    - `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
    - `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made the documentation for the corresponding changes.

2024-06-21 12:51 UTC, threeal requested changes

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/camera/node/camera_node.hpp
> +#include "rclcpp/rclcpp.hpp"
https://www.learncpp.com/cpp-tutorial/header-files/#includemethod

```suggestion
#include <rclcpp/rclcpp.hpp>
```

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/camera/provider/camera_config_provider.hpp
> +#include "keisan/keisan.hpp"
Ditto.
```suggestion
#include <keisan/keisan.hpp>
```

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/camera/provider/image_provider.hpp
> +#include "std_msgs/msg/header.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/config/grpc/call_data.hpp
> +#include "shisen_interfaces/shisen.pb.h"
Ditto.

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/config/grpc/config.hpp
> +#include "shisen_interfaces/shisen.pb.h"
Ditto.

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/node/shisen_cpp_node.hpp
> +#include "rclcpp/rclcpp.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/utility/capture_setting.hpp
> +#include "shisen_interfaces/msg/capture_setting.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/utility/interface.hpp
> +#include "shisen_interfaces/srv/configure_capture_setting.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/viewer/consumer/image_consumer.hpp
> +#include "sensor_msgs/msg/image.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on include/shisen_cpp/viewer/node/viewer_node.hpp
> +#include "sensor_msgs/msg/image.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on src/shisen_cpp/camera/node/camera_node.cpp
> +#include "nlohmann/json.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on src/shisen_cpp/camera/provider/image_provider.cpp
> +#include "opencv2/opencv.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on src/shisen_cpp/config/grpc/call_data_get_capture_setting.cpp
> +#include "shisen_interfaces/shisen.pb.h"
Ditto.

2024-06-21 12:51 UTC, threeal commented on src/shisen_cpp/config/grpc/call_data_get_image.cpp
> +#include "shisen_interfaces/shisen.pb.h"
Ditto.

2024-06-21 12:51 UTC, threeal commented on src/shisen_cpp/config/grpc/call_data_save_capture_setting.cpp
> +#include "shisen_interfaces/shisen.pb.h"
Ditto.

2024-06-21 12:51 UTC, threeal commented on src/shisen_cpp/config/grpc/call_data_set_capture_setting.cpp
> +#include "shisen_interfaces/shisen.pb.h"
Ditto.

2024-06-21 12:51 UTC, threeal commented on src/shisen_cpp/config/grpc/config.cpp
> +#include "rclcpp/rclcpp.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on src/shisen_cpp_main.cpp
> +#include "rclcpp/rclcpp.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on src/viewer_main.cpp
> +#include "rclcpp/rclcpp.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on test/capture_setting_test.cpp
> +#include "gtest/gtest.h"
Ditto.

2024-06-21 12:51 UTC, threeal commented on test/compile_test.cpp
> +#include "rclcpp/rclcpp.hpp"
Ditto.

2024-06-21 12:51 UTC, threeal commented on test/emptiable_test.cpp
> +#include "gtest/gtest.h"
Ditto.

2024-06-22 08:51 UTC, threeal commented on src/shisen_cpp/camera/node/camera_node.cpp
> +#include "jitsuyo/config.hpp"
Should use angled brackets:
```suggestion
#include <jitsuyo/config.hpp>
```

2024-06-23 14:58 UTC, threeal approved these changes, later dismissed

2024-06-24 13:47 UTC, borednuna approved these changes, later dismissed

2024-06-24 17:30 UTC, FaaizHaikal approved these changes

2024-06-24 17:32 UTC, mbsaloka approved these changes

2024-06-24 17:32 UTC, merged